---
title: 'Mariah Carey'
date: 2019-03-22 01:21:23
description: Mariah Carey (born March 27, 1969[2] or 1970)[3] is an American singer, songwriter, actress, record producer, and entrepreneur.
category: music
background: #e84393
---

Mariah Carey (born March 27, 1969[2] or 1970)[3] is an American singer, songwriter, actress, record producer, and entrepreneur. Referred to as the "Songbird Supreme" by the Guinness World Records, she is noted for her five-octave vocal range, melismatic singing style, and signature use of the whistle register. She rose to fame in the early 1990s after signing to Columbia Records and releasing her eponymous debut album, which topped the U.S. Billboard 200 for eleven consecutive weeks. Soon after, Carey became the only artist ever to have their first five singles reach number one on the U.S. Billboard Hot 100 chart, from "Vision of Love" to "Emotions".[4]

Following her marriage to Sony Music head Tommy Mottola, Carey achieved worldwide success with follow-up albums Music Box (1993), Merry Christmas (1994), and Daydream (1995). These albums spawned some of Carey's most successful singles, including "Hero", "Without You", "All I Want for Christmas Is You", "Fantasy", "Always Be My Baby", as well as "One Sweet Day", which became the longest-running U.S. number-one single in history (sixteen weeks) from 1996 until 2019. After separating from Mottola, Carey adopted a new image and incorporated more elements of hip hop into her music with the release of Butterfly (1997). Billboard named her the country's most successful artist of the 1990s, while the World Music Awards honored her as the world's best-selling recording artist of the 1990s.

After eleven consecutive years charting a U.S. number-one single, Carey parted ways with Columbia in 2000 and signed a $100 million recording contract with Virgin Records. However, following her highly publicized physical and emotional breakdown, as well as the critical and commercial failure of her film Glitter (2001) and its accompanying soundtrack, her contract was bought out for $50 million by Virgin and she signed with Island Records the next year. After a relatively unsuccessful period, she returned to the top of music charts with The Emancipation of Mimi (2005), which became the world's second best-selling album of 2005. Its single, "We Belong Together", made her the only artist to top the Billboard Hot 100 Decade-End chart twice. With the release of "Touch My Body" (2008), Carey gained her eighteenth number-one single in the United States, more than any other solo artist. The next year, she starred in the critically acclaimed film Precious, which won her Breakthrough Actress Performance Award at the Palm Springs International Film Festival.

Throughout her career, Carey has sold more than 200 million records worldwide, making her one of the best-selling music artists of all time. According to the Recording Industry Association of America (RIAA), she is the third-best-selling female artist in the United States, with 64 million certified albums.[5] In addition to this, she is listed as the female songwriter and producer with the most number one songs in U.S. chart history. In 2012, she was ranked second on VH1's list of the 100 Greatest Women in Music. Aside from her commercial accomplishments, Carey has won five Grammy Awards, nineteen World Music Awards, ten American Music Awards,[6] and fifteen Billboard Music Awards.[7] She has consistently been credited with inspiring a generation of singers, and is hailed as being one of the pioneers of pop and contemporary R&B music.[8]
